# Generated by Django 6.0 on 2026-01-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fleet_size', models.IntegerField()),
                ('on_time_deliveries', models.IntegerField()),
                ('incidents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('risk_exposure', models.FloatField()),
                ('claims_processed', models.IntegerField()),
                ('compliance_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('congestion_index', models.IntegerField()),
                ('arrivals_today', models.IntegerField()),
                ('avg_wait_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=20)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('speed', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
